name: articlely
description: "A new Flutter project."

publish_to: 'none'


environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_svg: ^2.0.7
  pretty_dio_logger: ^1.3.1

  animated_text_kit: ^4.2.3
  flutterfire_cli: ^1.2.0
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  shimmer: ^3.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  url_launcher: ^6.2.5





  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/jpgImages/
    - assets/svgImages/



