// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7_aRr-4CtcPHmpc6khthcV2gjjMycp0',
    appId: '1:111769515349:web:491a2ab11e9ecdd8bf2bdc',
    messagingSenderId: '111769515349',
    projectId: 'articlely-f16de',
    authDomain: 'articlely-f16de.firebaseapp.com',
    storageBucket: 'articlely-f16de.firebasestorage.app',
    measurementId: 'G-XVZG641NPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmHOu9MArxt5EiUj7NvCGXNgx2nBg1dbo',
    appId: '1:111769515349:android:f57ff344fb8bcf8fbf2bdc',
    messagingSenderId: '111769515349',
    projectId: 'articlely-f16de',
    storageBucket: 'articlely-f16de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfa9xsejr29UL2RNG6yhIlOfFF2GrpP4U',
    appId: '1:111769515349:ios:d1c66ec7ebb80c0ebf2bdc',
    messagingSenderId: '111769515349',
    projectId: 'articlely-f16de',
    storageBucket: 'articlely-f16de.firebasestorage.app',
    iosBundleId: 'com.example.articlely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfa9xsejr29UL2RNG6yhIlOfFF2GrpP4U',
    appId: '1:111769515349:ios:d1c66ec7ebb80c0ebf2bdc',
    messagingSenderId: '111769515349',
    projectId: 'articlely-f16de',
    storageBucket: 'articlely-f16de.firebasestorage.app',
    iosBundleId: 'com.example.articlely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY7_aRr-4CtcPHmpc6khthcV2gjjMycp0',
    appId: '1:111769515349:web:7f1560470fe39a18bf2bdc',
    messagingSenderId: '111769515349',
    projectId: 'articlely-f16de',
    authDomain: 'articlely-f16de.firebaseapp.com',
    storageBucket: 'articlely-f16de.firebasestorage.app',
    measurementId: 'G-HTZLPWK041',
  );
}
